apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-pi
  namespace: argocd
  labels:
    app.kubernetes.io/name: spark-pi
    app.kubernetes.io/part-of: demo-sparkmeasure
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: spark-pi
  project: default
  source:
    path: charts/spark-pi
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision.default }}
    helm:
      releaseName: fink-broker
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true