spec:
  destination:
    server: https://kubernetes.default.svc
  sparkNamespace: spark
  source:
    targetRevision:
      default: nil
      # Revision for the fink-alert-simulator chart
      finkalertsimulator: nil
      # Revision for the fink-broker chart
      finkbroker: nil
