apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sql
spec:
  sparkConf:
    spark.jars.packages: "ch.cern.sparkmeasure:spark-measure_2.12:0.24"
    spark.jars.ivy: "/tmp/ivy"
  type: Python
  mode: cluster
  image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: "{{ .Values.image.pullPolicy }}"
  mainApplicationFile: local:///opt/spark/examples/src/main/python/spark-sql.py
  sparkVersion: "3.4.1"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.4.1
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.4.1
