apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sql
spec:
  sparkConf:
    spark.jars.packages: "ch.cern.sparkmeasure:spark-measure_2.12:0.25"
    spark.jars.ivy: "/tmp/ivy"
  type: Python
  mode: cluster
  image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: "{{ .Values.image.pullPolicy }}"
  mainApplicationFile: local:///opt/spark/examples/src/main/python/spark-sql.py
  sparkVersion: "3.4.1"
  driver:
    lifecycle:
      postStart:
        exec:
          command:
            - /bin/sh
            - -c
            - |
              cat /config-jmx/config.yaml >> /opt/spark/conf/prometheus.yaml
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.4.1
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: jmx-config
        mountPath: /config-jmx
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.4.1
    volumeMounts:
      - name: jmx-config
        mountPath: /config-jmx
  volumes:
    - name: jmx-config
      configMap:
        name: spark-jmx-config
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      # This is the path to the jmx_exporter jar in the spark container image, added at build time
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-1.1.0.jar"
      port: 8090


