name: "e2e tests"
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  main:
    name: Run spark-measure demo
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Required by ciux
        with:
          fetch-depth: 0
      - name: Stop apparmor
        run: |
          sudo /etc/init.d/apparmor stop
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.21.4'
      - name: Run ciux and create k8s/kind cluster
        run: |
          ./prereq.sh
      - name: Run argocd
        run: |
          ./argocd.sh
      - name: Push image
        run: |
          ./push-image.sh
